airbnb:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'default') }}"
      user: dbt

      role: "{{ env_var('DBT_ROLE', 'DEFAULT_ROLE') }}"
      private_key: "{{ env_var('PRIVATE_KEY', '') }}"
      private_key_passphrase: "{{ env_var('PRIVATE_KEY_PASSWORD', '') }}"

      database: "{{ env_var('SNOWFLAKE_DATABASE', 'default') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'default') }}"
      threads: 1
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'default') }}"
  target: dev